# Generated by Django 2.2 on 2019-05-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190522_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='company',
            new_name='openpay_customer_id',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='holder_name',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription',
        ),
        migrations.AddField(
            model_name='cards',
            name='openpay_card_id',
            field=models.CharField(default='ignoreid', max_length=30),
            preserve_default=False,
        ),
    ]
