# Generated by Django 2.2 on 2019-05-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190525_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_name',
            field=models.CharField(default='ignore', max_length=150),
            preserve_default=False,
        ),
    ]
